/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SupportImport } from './routes/support'
import { Route as RealEstateDashboardImport } from './routes/real-estate-dashboard'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as PricingImport } from './routes/pricing'
import { Route as PortfolioImport } from './routes/portfolio'
import { Route as DemoImport } from './routes/demo'
import { Route as ConstructionDashboardImport } from './routes/construction-dashboard'
import { Route as CompanyImport } from './routes/company'
import { Route as AccessibilityImport } from './routes/accessibility'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SupportRoute = SupportImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRoute,
} as any)

const RealEstateDashboardRoute = RealEstateDashboardImport.update({
  id: '/real-estate-dashboard',
  path: '/real-estate-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const PricingRoute = PricingImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioRoute = PortfolioImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRoute,
} as any)

const DemoRoute = DemoImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRoute,
} as any)

const ConstructionDashboardRoute = ConstructionDashboardImport.update({
  id: '/construction-dashboard',
  path: '/construction-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const CompanyRoute = CompanyImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRoute,
} as any)

const AccessibilityRoute = AccessibilityImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityImport
      parentRoute: typeof rootRoute
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyImport
      parentRoute: typeof rootRoute
    }
    '/construction-dashboard': {
      id: '/construction-dashboard'
      path: '/construction-dashboard'
      fullPath: '/construction-dashboard'
      preLoaderRoute: typeof ConstructionDashboardImport
      parentRoute: typeof rootRoute
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoImport
      parentRoute: typeof rootRoute
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioImport
      parentRoute: typeof rootRoute
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/real-estate-dashboard': {
      id: '/real-estate-dashboard'
      path: '/real-estate-dashboard'
      fullPath: '/real-estate-dashboard'
      preLoaderRoute: typeof RealEstateDashboardImport
      parentRoute: typeof rootRoute
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/company': typeof CompanyRoute
  '/construction-dashboard': typeof ConstructionDashboardRoute
  '/demo': typeof DemoRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/real-estate-dashboard': typeof RealEstateDashboardRoute
  '/support': typeof SupportRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/company': typeof CompanyRoute
  '/construction-dashboard': typeof ConstructionDashboardRoute
  '/demo': typeof DemoRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/real-estate-dashboard': typeof RealEstateDashboardRoute
  '/support': typeof SupportRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/company': typeof CompanyRoute
  '/construction-dashboard': typeof ConstructionDashboardRoute
  '/demo': typeof DemoRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/real-estate-dashboard': typeof RealEstateDashboardRoute
  '/support': typeof SupportRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/company'
    | '/construction-dashboard'
    | '/demo'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/real-estate-dashboard'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/company'
    | '/construction-dashboard'
    | '/demo'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/real-estate-dashboard'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/company'
    | '/construction-dashboard'
    | '/demo'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/real-estate-dashboard'
    | '/support'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CompanyRoute: typeof CompanyRoute
  ConstructionDashboardRoute: typeof ConstructionDashboardRoute
  DemoRoute: typeof DemoRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RealEstateDashboardRoute: typeof RealEstateDashboardRoute
  SupportRoute: typeof SupportRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  CompanyRoute: CompanyRoute,
  ConstructionDashboardRoute: ConstructionDashboardRoute,
  DemoRoute: DemoRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RealEstateDashboardRoute: RealEstateDashboardRoute,
  SupportRoute: SupportRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/accessibility",
        "/company",
        "/construction-dashboard",
        "/demo",
        "/portfolio",
        "/pricing",
        "/privacy",
        "/real-estate-dashboard",
        "/support"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/accessibility": {
      "filePath": "accessibility.tsx"
    },
    "/company": {
      "filePath": "company.tsx"
    },
    "/construction-dashboard": {
      "filePath": "construction-dashboard.tsx"
    },
    "/demo": {
      "filePath": "demo.tsx"
    },
    "/portfolio": {
      "filePath": "portfolio.tsx"
    },
    "/pricing": {
      "filePath": "pricing.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/real-estate-dashboard": {
      "filePath": "real-estate-dashboard.tsx"
    },
    "/support": {
      "filePath": "support.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
