/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SupportImport } from './routes/support'
import { Route as ShopifyProfitRecoveryImport } from './routes/shopify-profit-recovery'
import { Route as SecuritySchedulingDashboardImport } from './routes/security-scheduling-dashboard'
import { Route as RealEstateDashboardImport } from './routes/real-estate-dashboard'
import { Route as QuickEmbedImport } from './routes/quick-embed'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as PortfolioImport } from './routes/portfolio'
import { Route as HowWeWorkImport } from './routes/how-we-work'
import { Route as DemoImport } from './routes/demo'
import { Route as ConstructionDashboardImport } from './routes/construction-dashboard'
import { Route as CompanyImport } from './routes/company'
import { Route as AscentPharmaceuticalsLandingImport } from './routes/ascent-pharmaceuticals-landing'
import { Route as AgenticBiImport } from './routes/agentic-bi'
import { Route as AcmeLifecycleImport } from './routes/acme-lifecycle'
import { Route as AccessibilityImport } from './routes/accessibility'
import { Route as IndexImport } from './routes/index'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as BlogPostIdImport } from './routes/blog/$postId'

// Create/Update Routes

const SupportRoute = SupportImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRoute,
} as any)

const ShopifyProfitRecoveryRoute = ShopifyProfitRecoveryImport.update({
  id: '/shopify-profit-recovery',
  path: '/shopify-profit-recovery',
  getParentRoute: () => rootRoute,
} as any)

const SecuritySchedulingDashboardRoute =
  SecuritySchedulingDashboardImport.update({
    id: '/security-scheduling-dashboard',
    path: '/security-scheduling-dashboard',
    getParentRoute: () => rootRoute,
  } as any)

const RealEstateDashboardRoute = RealEstateDashboardImport.update({
  id: '/real-estate-dashboard',
  path: '/real-estate-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const QuickEmbedRoute = QuickEmbedImport.update({
  id: '/quick-embed',
  path: '/quick-embed',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioRoute = PortfolioImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRoute,
} as any)

const HowWeWorkRoute = HowWeWorkImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRoute,
} as any)

const DemoRoute = DemoImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRoute,
} as any)

const ConstructionDashboardRoute = ConstructionDashboardImport.update({
  id: '/construction-dashboard',
  path: '/construction-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const CompanyRoute = CompanyImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRoute,
} as any)

const AscentPharmaceuticalsLandingRoute =
  AscentPharmaceuticalsLandingImport.update({
    id: '/ascent-pharmaceuticals-landing',
    path: '/ascent-pharmaceuticals-landing',
    getParentRoute: () => rootRoute,
  } as any)

const AgenticBiRoute = AgenticBiImport.update({
  id: '/agentic-bi',
  path: '/agentic-bi',
  getParentRoute: () => rootRoute,
} as any)

const AcmeLifecycleRoute = AcmeLifecycleImport.update({
  id: '/acme-lifecycle',
  path: '/acme-lifecycle',
  getParentRoute: () => rootRoute,
} as any)

const AccessibilityRoute = AccessibilityImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRoute,
} as any)

const BlogPostIdRoute = BlogPostIdImport.update({
  id: '/blog/$postId',
  path: '/blog/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityImport
      parentRoute: typeof rootRoute
    }
    '/acme-lifecycle': {
      id: '/acme-lifecycle'
      path: '/acme-lifecycle'
      fullPath: '/acme-lifecycle'
      preLoaderRoute: typeof AcmeLifecycleImport
      parentRoute: typeof rootRoute
    }
    '/agentic-bi': {
      id: '/agentic-bi'
      path: '/agentic-bi'
      fullPath: '/agentic-bi'
      preLoaderRoute: typeof AgenticBiImport
      parentRoute: typeof rootRoute
    }
    '/ascent-pharmaceuticals-landing': {
      id: '/ascent-pharmaceuticals-landing'
      path: '/ascent-pharmaceuticals-landing'
      fullPath: '/ascent-pharmaceuticals-landing'
      preLoaderRoute: typeof AscentPharmaceuticalsLandingImport
      parentRoute: typeof rootRoute
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyImport
      parentRoute: typeof rootRoute
    }
    '/construction-dashboard': {
      id: '/construction-dashboard'
      path: '/construction-dashboard'
      fullPath: '/construction-dashboard'
      preLoaderRoute: typeof ConstructionDashboardImport
      parentRoute: typeof rootRoute
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoImport
      parentRoute: typeof rootRoute
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkImport
      parentRoute: typeof rootRoute
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/quick-embed': {
      id: '/quick-embed'
      path: '/quick-embed'
      fullPath: '/quick-embed'
      preLoaderRoute: typeof QuickEmbedImport
      parentRoute: typeof rootRoute
    }
    '/real-estate-dashboard': {
      id: '/real-estate-dashboard'
      path: '/real-estate-dashboard'
      fullPath: '/real-estate-dashboard'
      preLoaderRoute: typeof RealEstateDashboardImport
      parentRoute: typeof rootRoute
    }
    '/security-scheduling-dashboard': {
      id: '/security-scheduling-dashboard'
      path: '/security-scheduling-dashboard'
      fullPath: '/security-scheduling-dashboard'
      preLoaderRoute: typeof SecuritySchedulingDashboardImport
      parentRoute: typeof rootRoute
    }
    '/shopify-profit-recovery': {
      id: '/shopify-profit-recovery'
      path: '/shopify-profit-recovery'
      fullPath: '/shopify-profit-recovery'
      preLoaderRoute: typeof ShopifyProfitRecoveryImport
      parentRoute: typeof rootRoute
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportImport
      parentRoute: typeof rootRoute
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdImport
      parentRoute: typeof rootRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/acme-lifecycle': typeof AcmeLifecycleRoute
  '/agentic-bi': typeof AgenticBiRoute
  '/ascent-pharmaceuticals-landing': typeof AscentPharmaceuticalsLandingRoute
  '/company': typeof CompanyRoute
  '/construction-dashboard': typeof ConstructionDashboardRoute
  '/demo': typeof DemoRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/quick-embed': typeof QuickEmbedRoute
  '/real-estate-dashboard': typeof RealEstateDashboardRoute
  '/security-scheduling-dashboard': typeof SecuritySchedulingDashboardRoute
  '/shopify-profit-recovery': typeof ShopifyProfitRecoveryRoute
  '/support': typeof SupportRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/blog': typeof BlogIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/acme-lifecycle': typeof AcmeLifecycleRoute
  '/agentic-bi': typeof AgenticBiRoute
  '/ascent-pharmaceuticals-landing': typeof AscentPharmaceuticalsLandingRoute
  '/company': typeof CompanyRoute
  '/construction-dashboard': typeof ConstructionDashboardRoute
  '/demo': typeof DemoRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/quick-embed': typeof QuickEmbedRoute
  '/real-estate-dashboard': typeof RealEstateDashboardRoute
  '/security-scheduling-dashboard': typeof SecuritySchedulingDashboardRoute
  '/shopify-profit-recovery': typeof ShopifyProfitRecoveryRoute
  '/support': typeof SupportRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/blog': typeof BlogIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/acme-lifecycle': typeof AcmeLifecycleRoute
  '/agentic-bi': typeof AgenticBiRoute
  '/ascent-pharmaceuticals-landing': typeof AscentPharmaceuticalsLandingRoute
  '/company': typeof CompanyRoute
  '/construction-dashboard': typeof ConstructionDashboardRoute
  '/demo': typeof DemoRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/quick-embed': typeof QuickEmbedRoute
  '/real-estate-dashboard': typeof RealEstateDashboardRoute
  '/security-scheduling-dashboard': typeof SecuritySchedulingDashboardRoute
  '/shopify-profit-recovery': typeof ShopifyProfitRecoveryRoute
  '/support': typeof SupportRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/blog/': typeof BlogIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/acme-lifecycle'
    | '/agentic-bi'
    | '/ascent-pharmaceuticals-landing'
    | '/company'
    | '/construction-dashboard'
    | '/demo'
    | '/how-we-work'
    | '/portfolio'
    | '/privacy'
    | '/quick-embed'
    | '/real-estate-dashboard'
    | '/security-scheduling-dashboard'
    | '/shopify-profit-recovery'
    | '/support'
    | '/blog/$postId'
    | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/acme-lifecycle'
    | '/agentic-bi'
    | '/ascent-pharmaceuticals-landing'
    | '/company'
    | '/construction-dashboard'
    | '/demo'
    | '/how-we-work'
    | '/portfolio'
    | '/privacy'
    | '/quick-embed'
    | '/real-estate-dashboard'
    | '/security-scheduling-dashboard'
    | '/shopify-profit-recovery'
    | '/support'
    | '/blog/$postId'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/acme-lifecycle'
    | '/agentic-bi'
    | '/ascent-pharmaceuticals-landing'
    | '/company'
    | '/construction-dashboard'
    | '/demo'
    | '/how-we-work'
    | '/portfolio'
    | '/privacy'
    | '/quick-embed'
    | '/real-estate-dashboard'
    | '/security-scheduling-dashboard'
    | '/shopify-profit-recovery'
    | '/support'
    | '/blog/$postId'
    | '/blog/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AcmeLifecycleRoute: typeof AcmeLifecycleRoute
  AgenticBiRoute: typeof AgenticBiRoute
  AscentPharmaceuticalsLandingRoute: typeof AscentPharmaceuticalsLandingRoute
  CompanyRoute: typeof CompanyRoute
  ConstructionDashboardRoute: typeof ConstructionDashboardRoute
  DemoRoute: typeof DemoRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  QuickEmbedRoute: typeof QuickEmbedRoute
  RealEstateDashboardRoute: typeof RealEstateDashboardRoute
  SecuritySchedulingDashboardRoute: typeof SecuritySchedulingDashboardRoute
  ShopifyProfitRecoveryRoute: typeof ShopifyProfitRecoveryRoute
  SupportRoute: typeof SupportRoute
  BlogPostIdRoute: typeof BlogPostIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AcmeLifecycleRoute: AcmeLifecycleRoute,
  AgenticBiRoute: AgenticBiRoute,
  AscentPharmaceuticalsLandingRoute: AscentPharmaceuticalsLandingRoute,
  CompanyRoute: CompanyRoute,
  ConstructionDashboardRoute: ConstructionDashboardRoute,
  DemoRoute: DemoRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  QuickEmbedRoute: QuickEmbedRoute,
  RealEstateDashboardRoute: RealEstateDashboardRoute,
  SecuritySchedulingDashboardRoute: SecuritySchedulingDashboardRoute,
  ShopifyProfitRecoveryRoute: ShopifyProfitRecoveryRoute,
  SupportRoute: SupportRoute,
  BlogPostIdRoute: BlogPostIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/accessibility",
        "/acme-lifecycle",
        "/agentic-bi",
        "/ascent-pharmaceuticals-landing",
        "/company",
        "/construction-dashboard",
        "/demo",
        "/how-we-work",
        "/portfolio",
        "/privacy",
        "/quick-embed",
        "/real-estate-dashboard",
        "/security-scheduling-dashboard",
        "/shopify-profit-recovery",
        "/support",
        "/blog/$postId",
        "/blog/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/accessibility": {
      "filePath": "accessibility.tsx"
    },
    "/acme-lifecycle": {
      "filePath": "acme-lifecycle.tsx"
    },
    "/agentic-bi": {
      "filePath": "agentic-bi.tsx"
    },
    "/ascent-pharmaceuticals-landing": {
      "filePath": "ascent-pharmaceuticals-landing.tsx"
    },
    "/company": {
      "filePath": "company.tsx"
    },
    "/construction-dashboard": {
      "filePath": "construction-dashboard.tsx"
    },
    "/demo": {
      "filePath": "demo.tsx"
    },
    "/how-we-work": {
      "filePath": "how-we-work.tsx"
    },
    "/portfolio": {
      "filePath": "portfolio.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/quick-embed": {
      "filePath": "quick-embed.tsx"
    },
    "/real-estate-dashboard": {
      "filePath": "real-estate-dashboard.tsx"
    },
    "/security-scheduling-dashboard": {
      "filePath": "security-scheduling-dashboard.tsx"
    },
    "/shopify-profit-recovery": {
      "filePath": "shopify-profit-recovery.tsx"
    },
    "/support": {
      "filePath": "support.tsx"
    },
    "/blog/$postId": {
      "filePath": "blog/$postId.tsx"
    },
    "/blog/": {
      "filePath": "blog/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
